[common]
system = "x86_64-linux"
timezone = "America/New_York"

[framework]
hostname = "fw"
username = "qd"

[agent-do]
hostname = "herc-agent"
username = "herc-admin"
volume = "volume-nyc3-01"
ip = "142.93.190.80"

[agent-latitude]
hostname = "herc-agent"
username = "herc-admin"
