name: "Build and cache"
on:
  push:
    branches:
    - main

jobs:

  build_nixos_configuration:
    name: "NixOS configuration"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: effective-altruism
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations."fw".config.system.build.toplevel
      env:
        FACTORIO_KEY: '${{ secrets.FACTORIO_KEY }}'

  build_shell:
    name: "Development shell"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: effective-altruism
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix develop -c echo "OK"
