name: "Build and cache"
on:
  push:
  - main

jobs:

  build_nixos_configuration:
    name: "NixOS configuration"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: effective-altruism
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations."fw".config.system.build.toplevel

  build_shell:
    name: "Development shell"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: effective-altruism
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix develop -c echo "OK"
