name: "Lint"
on:
  push:
jobs:
  lint:
    name: "`nixfmt` & `prettier`"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-env -i nixfmt -i nodePackages.prettier -f '<nixpkgs>'
      - run: nixfmt --check $(find . -type f | grep '[.]nix')
      - run: prettier --check .
