name: "Lint"
on:
  push:
jobs:
  lint:
    name: "`nixfmt` & `prettier`"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Install linters"
        run: |
          nix-env -iA nixpkgs.nixfmt -f '<nixpkgs>'
          nix-env -iA nixpkgs.nodePackages.prettier -f '<nixpkgs>'
      - name: "Check `.nix` files"
        run: nixfmt --check $(find . -type f | grep '[.]nix')
      - name: "Check all other files"
        run: prettier --check .
